<?php

/**
 * Implements hook_permission().
 */
function drupalgotchi_permission() {
  return array(
    'administer drupalgotchi' => array(
      'title' => t('Change the Drupalgotchi settings'),
    ),
    'make drupalgotchi happy' => array(
      'title' => t('Perform tasks to make the site happier'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function drupalgotchi_menu() {
  $items['drupalgotchi'] = array(
    'title' => 'Drupalgotchi',
    'description' => 'The requisite hello-world page.',
    'route_name' => 'drupalgotchi.hello',
  );

  $items['admin/config/system/drupalgotchi'] = array(
    'title' => 'Configure Drupalgotchi',
    'description' => 'Setup the Drupalgotchi for your site.',
    'route_name' => 'drupalgotchi.settings',
  );

  $items['drupalgotchi-about'] = array(
    'title' => 'About Drupalgotchi module',
    'description' => 'A brief description of the drupalgotchi module',
    'route_name' => 'drupalgotchi.about',
    'menu_name' => 'main',
  );

  return $items;
}


/**
 * Implements hook_theme().
 */
function drupalgotchi_theme() {
  return array(
    'drupalgotchi_hello' => array(
      'variables' => array('name' => NULL, 'person' => NULL),
      'template' => 'drupalgotchi-hello',
    ),
    'drupalgotchi_hello_block' => array(
      'variables' => array('person' => NULL),
      'template' => 'drupalgotchi-hello-block',
    ),
    'drupalgotchi_status_block' => array(
      'variables' => array('attention' => NULL, 'name' => NULL),
      'template' => 'drupalgotchi-status-block',
    ),
    'drupalgotchi_about' => array(
      'variables' => array('name' => NULL),
      'template' => 'drupalgotchi-about',
    ),
  );
}
