<?php

/**
 * Implements hook_permission().
 */
function drupalgotchi_permission() {
  return array(
    'administer drupalgotchi' => array(
      'title' => t('Change the Drupalgotchi settings'),
    ),
    'make drupalgotchi happy' => array(
      'title' => t('Perform tasks to make the site happier'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function drupalgotchi_menu() {
  $items['admin/config/system/drupalgotchi'] = array(
    'title' => 'Configure Drupalgotchi',
    'description' => 'Setup the Drupalgotchi for your site.',
    'route_name' => 'drupalgotchi_settings',
  );

  return $items;
}
